### ISSUE TITLE
APRS4R not work with kiss tnc under debian jessy or stretch

### ISSUE THREAD

**Issue by dg1kwa** [gmcintire/aprs4r#1]
[ERROR] 2017-11-24 08:55:41 KISSSerialConnection:: /usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:678:in `block in write_serial'
<internal:prelude>:10:in `synchronize'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:674:in `write_serial'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:264:in `init_tnc2_northlink'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:188:in `init_kiss'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:228:in `reinit_kiss'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:589:in `rescue in read_port_frame'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:545:in `read_port_frame'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:510:in `run'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:135:in `block in initialize'
[WARN] 2017-11-24 08:55:42 KISSSerialConnection:: readFrame: ex: undefined method `readbyte' for nil:NilClass
[ERROR] 2017-11-24 08:55:47 KISSSerialConnection:: error writing to serial port: private method `puts' called for nil:NilClass
[ERROR] 2017-11-24 08:55:47 KISSSerialConnection:: /usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:678:in `block in write_serial'
<internal:prelude>:10:in `synchronize'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:674:in `write_serial'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:264:in `init_tnc2_northlink'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:188:in `init_kiss'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:228:in `reinit_kiss'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:589:in `rescue in read_port_frame'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:545:in `read_port_frame'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:510:in `run'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:135:in `block in initialize'
[WARN] 2017-11-24 08:55:48 KISSSerialConnection:: readFrame: ex: undefined method `readbyte' for nil:NilClass
[ERROR] 2017-11-24 08:55:53 KISSSerialConnection:: error writing to serial port: private method `puts' called for nil:NilClass
[ERROR] 2017-11-24 08:55:53 KISSSerialConnection:: /usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:678:in `block in write_serial'
<internal:prelude>:10:in `synchronize'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:674:in `write_serial'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:264:in `init_tnc2_northlink'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:188:in `init_kiss'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:228:in `reinit_kiss'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:589:in `rescue in read_port_frame'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:545:in `read_port_frame'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:510:in `run'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:135:in `block in initialize'
[WARN] 2017-11-24 08:55:54 KISSSerialConnection:: readFrame: ex: undefined method `readbyte' for nil:NilClass
[ERROR] 2017-11-24 08:55:59 KISSSerialConnection:: error writing to serial port: private method `puts' called for nil:NilClass
[ERROR] 2017-11-24 08:55:59 KISSSerialConnection:: /usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:678:in `block in write_serial'
<internal:prelude>:10:in `synchronize'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:674:in `write_serial'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:264:in `init_tnc2_northlink'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:188:in `init_kiss'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:228:in `reinit_kiss'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:589:in `rescue in read_port_frame'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:545:in `read_port_frame'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:510:in `run'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:135:in `block in initialize'
[WARN] 2017-11-24 08:56:00 KISSSerialConnection:: readFrame: ex: undefined method `readbyte' for nil:NilClass
[ERROR] 2017-11-24 08:56:05 KISSSerialConnection:: error writing to serial port: private method `puts' called for nil:NilClass
[ERROR] 2017-11-24 08:56:05 KISSSerialConnection:: /usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:678:in `block in write_serial'
<internal:prelude>:10:in `synchronize'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:674:in `write_serial'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:264:in `init_tnc2_northlink'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:188:in `init_kiss'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:228:in `reinit_kiss'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:589:in `rescue in read_port_frame'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:545:in `read_port_frame'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:510:in `run'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:135:in `block in initialize'
[WARN] 2017-11-24 08:56:06 KISSSerialConnection:: readFrame: ex: undefined method `readbyte' for nil:NilClass
[ERROR] 2017-11-24 08:56:11 KISSSerialConnection:: error writing to serial port: private method `puts' called for nil:NilClass
[ERROR] 2017-11-24 08:56:11 KISSSerialConnection:: /usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:678:in `block in write_serial'
<internal:prelude>:10:in `synchronize'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:674:in `write_serial'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:264:in `init_tnc2_northlink'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:188:in `init_kiss'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:228:in `reinit_kiss'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:589:in `rescue in read_port_frame'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:545:in `read_port_frame'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:510:in `run'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:135:in `block in initialize'
[WARN] 2017-11-24 08:56:12 KISSSerialConnection:: readFrame: ex: undefined method `readbyte' for nil:NilClass
[ERROR] 2017-11-24 08:56:17 KISSSerialConnection:: error writing to serial port: private method `puts' called for nil:NilClass
[ERROR] 2017-11-24 08:56:17 KISSSerialConnection:: /usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:678:in `block in write_serial'
<internal:prelude>:10:in `synchronize'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:674:in `write_serial'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:264:in `init_tnc2_northlink'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:188:in `init_kiss'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:228:in `reinit_kiss'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:589:in `rescue in read_port_frame'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:545:in `read_port_frame'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:510:in `run'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:135:in `block in initialize'
[WARN] 2017-11-24 08:56:18 KISSSerialConnection:: readFrame: ex: undefined method `readbyte' for nil:NilClass
[ERROR] 2017-11-24 08:56:23 KISSSerialConnection:: error writing to serial port: private method `puts' called for nil:NilClass
[ERROR] 2017-11-24 08:56:23 KISSSerialConnection:: /usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:678:in `block in write_serial'
<internal:prelude>:10:in `synchronize'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:674:in `write_serial'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:264:in `init_tnc2_northlink'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:188:in `init_kiss'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:228:in `reinit_kiss'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:589:in `rescue in read_port_frame'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:545:in `read_port_frame'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:510:in `run'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:135:in `block in initialize'
[WARN] 2017-11-24 08:56:24 KISSSerialConnection:: readFrame: ex: undefined method `readbyte' for nil:NilClass
[ERROR] 2017-11-24 08:56:29 KISSSerialConnection:: error writing to serial port: private method `puts' called for nil:NilClass
[ERROR] 2017-11-24 08:56:29 KISSSerialConnection:: /usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:678:in `block in write_serial'
<internal:prelude>:10:in `synchronize'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:674:in `write_serial'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:264:in `init_tnc2_northlink'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:188:in `init_kiss'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:228:in `reinit_kiss'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:589:in `rescue in read_port_frame'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:545:in `read_port_frame'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:510:in `run'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:135:in `block in initialize'
[WARN] 2017-11-24 08:56:30 KISSSerialConnection:: readFrame: ex: undefined method `readbyte' for nil:NilClass
[ERROR] 2017-11-24 08:56:35 KISSSerialConnection:: error writing to serial port: private method `puts' called for nil:NilClass
[ERROR] 2017-11-24 08:56:35 KISSSerialConnection:: /usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:678:in `block in write_serial'
<internal:prelude>:10:in `synchronize'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:674:in `write_serial'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:264:in `init_tnc2_northlink'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:188:in `init_kiss'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:228:in `reinit_kiss'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:589:in `rescue in read_port_frame'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:545:in `read_port_frame'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:510:in `run'
/usr/lib/ruby/vendor_ruby/aprs4r/KISSSerialConnection.rb:135:in `block in initialize'
[WARN] 2017-11-24 08:56:36 KISSSerialConnection:: readFrame: ex: undefined method `readbyte' for nil:NilClass
[ERROR] 2017-11-24 08:56:41 KISSSerialConnection:: error writing to serial port: private method `puts' called for nil:NilClass

**Comment by dg1kwa** [comment]
ups, can close just see was wrong ;-) sorry
